
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retirer", targetNamespace = "http://service/", className = "service.Retirer")
    @ResponseWrapper(localName = "retirerResponse", targetNamespace = "http://service/", className = "service.RetirerResponse")
    @Action(input = "http://service/BanqueService/retirerRequest", output = "http://service/BanqueService/retirerResponse")
    public double retirer(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversion", targetNamespace = "http://service/", className = "service.Conversion")
    @ResponseWrapper(localName = "conversionResponse", targetNamespace = "http://service/", className = "service.ConversionResponse")
    @Action(input = "http://service/BanqueService/conversionRequest", output = "http://service/BanqueService/conversionResponse")
    public double conversion(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verser", targetNamespace = "http://service/", className = "service.Verser")
    @ResponseWrapper(localName = "verserResponse", targetNamespace = "http://service/", className = "service.VerserResponse")
    @Action(input = "http://service/BanqueService/verserRequest", output = "http://service/BanqueService/verserResponse")
    public double verser(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentSolde", targetNamespace = "http://service/", className = "service.GetCurrentSolde")
    @ResponseWrapper(localName = "getCurrentSoldeResponse", targetNamespace = "http://service/", className = "service.GetCurrentSoldeResponse")
    @Action(input = "http://service/BanqueService/getCurrentSoldeRequest", output = "http://service/BanqueService/getCurrentSoldeResponse")
    public double getCurrentSolde();

}
